version: "3"
services:
    rfcsynchronizer:
        image: botvy/rfc-synchronizer
        build: .
        container_name: rfc-synchronizer
        environment:
            GH_TOKEN: my-github-token
            DB_HOST: localhost
            DB_PORT: 3306
            DB_USER: root
            DB_PASS: ""
            DB_NAME: rfc_synchronizer
    rfcsynchronizer-dev:
        image: botvy/rfc-synchronizer
        build:
            context: .
            dockerfile: dev.Dockerfile
        container_name: rfc-synchronizer
        environment:
            GH_TOKEN: my-github-token
            DB_HOST: localhost
            DB_PORT: 3306
            DB_USER: root
            DB_PASS: ""
            DB_NAME: rfc_synchronizer
        volumes:
            - "./src:/app/src"
            - "./node_modules:/app/node_modules"
