version: "3"
services:
    rfcsynchronizer:
        image: botvy/rfc-synchronizer
        build: .
        container_name: rfc-synchronizer
        depends_on:
            - database
        environment:
            GH_TOKEN: my-github-token
            DB_HOST: localhost
            DB_PORT: 3306
            DB_USER: root
            DB_PASS: ""
            DB_NAME: rfc_synchronizer
    rfcsynchronizer-dev:
        image: botvy/rfc-synchronizer:dev
        build:
            context: .
            dockerfile: dev.Dockerfile
        container_name: rfc-synchronizer
        depends_on:
            - database
        environment:
            GH_TOKEN: my-github-token
            DB_HOST: database
            DB_PORT: 3306
            DB_USER: root
            DB_PASS: root
            DB_NAME: rfc_synchronizer
            LOG_LEVEL: debug
        volumes:
            - "./src:/app/src"
            - "./node_modules:/app/node_modules"
    database:
        image: library/mysql:5.7.30
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: rfc_synchronizer
